### ISSUE TITLE
ImportError on boot

### ISSUE THREAD

**Issue by tiba1987** [ernitron/uPython-esp8266-httpserver#1]
When I start after installation I get the following error:

WebREPL daemon started on ws://0.0.0.0:8266
Started webrepl in normal mode
wake from hard reset
Connecting
Yes! Connected
Disconnecting  1
(2017, 1, 17, 18, 40, 56, 1, 17)
Traceback (most recent call last):
  File "main.py", line 3, in <module>
  File "real.py", line 120, in main
ImportError: no module named 'application'

Is there a file missing?

**Comment by ernitron** [comment]
Yes, application.py is missing. Actually I did a major refactor of code and did not upload the application loop. Consider that ultimately I use github just as a personal repository. In any case I will try to upload the missing part. Hold on...

**Comment by tiba1987** [comment]
Thanks a lot for the missing file. It is running now. I'm learning python
and ESP to make some home automation. This will help me a lot to understand
how your code works. Keep up the good work!

Regards,

Tim

2017-01-17 20:01 GMT+01:00 ernitron <notifications@github.com>:
